"""add_fraud_method_to_claims

Revision ID: 90246d1a8995
Revises: 9d4d2ddd1b06
Create Date: 2026-04-17 14:25:17.079520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90246d1a8995'
down_revision: Union[str, None] = '9d4d2ddd1b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('fraud_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'fraud_method')
    # ### end Alembic commands ###
